### ISSUE TITLE
Hotspot not working on Redmi 7A(pine)

### ISSUE THREAD

**Issue by hitchho** [GuaiYiHu/android_kernel_xiaomi_sdm439#1]
Not 100% sure if this is right repo for Redmi 7A Pine, but seems like hostin hotspot is not working with the MoKee ROM on device.
Broadcasted SSDI cannot be found by other devices nor connected directly with name.

**Comment by GuaiYiHu** [comment]
Already will be fixed in 20191103.

**Comment by Debrup1998** [comment]
Volte not working. .   and magisk not working as well

**Comment by hitchho** [comment]
Magisk works on Redmi 7A only through recovery mode. You better use AddonSU if looking to root the device with OS.
